import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html lang="en">
        <Head>
          <link rel="icon" href="/favicon.ico" />
          <meta content="IE=edge" httpEquiv="X-UA-Compatible" />
          <meta name="author" content="Dale Seo" />
          <meta name="keywords" content="HTML, CSS, JavaScript" />
          <meta name="description" content="Generated by create next app" />
          {/* <meta name="theme-color" content="#3182CE" />
          <meta name="msapplication-TileColor" content="#3182CE" /> */}
          {/* 'open graph' add */}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
